### ISSUE TITLE
Bug: executing permissions on Sigram file

### ISSUE THREAD

**Issue by rhoconlinux** [sialan-labs/sigram#7]
I think this is why the stuff is not working anywhere. 
You missed the chmod +x /opt/sialan/sigram/Sigram :)
Cheers!

ps. after that, no problems in Ubuntu.

**Comment by realbardia** [comment]
What version of packages you use? We fixed this problem on the last binary packages (Released 12 hourse ago) :/

**Comment by rhoconlinux** [comment]
Well, just installed. 0.53 deb package for 64 bits. The problem persist in that package. ^_^

**Comment by hotice** [comment]
This issue does not occur for me with the 0.53 deb package on Ubuntu 64bit. It was a fresh install for me though.
